### PR TITLE
Question update

### PR DESCRIPTION
**Pull request by ahujatejas06**
Don't merge

working... IDK whether this will work or not

Isnt tested

### CODE REVIEW

**Comment by 1-Harshit** [comment]
NO!
One DB-read takes 100 ms
Avg API should take 300 ms
MAX API time can be 1s

**Comment by 1-Harshit** [comment]
You were supposed to fetch ans of all `student*question` of particular `Proforma ID`

**Comment by 1-Harshit** [comment]
@ahujatejas06 what is this behaviour

**Comment by ahujatejas06** [comment]
Check out questionUpdate2 PR... Don't close this PR yet...

Had a quiz and project report submission...

**Pull request closed without merging**
