### PR TITLE
Create go-lint.yml

### PR DESCRIPTION
**Pull request by abhishekshree**

### CODE REVIEW

**Comment by abhishekshree** [comment]
Merging, but lint needs to be fixed

**Comment by 1-Harshit** [comment]
Why redundant? @***@***.******@***.***> get lint fixed


---
Harshit Raj
Junior Undergraduate
CSE, IIT Kanpur
harshitraj.me<https://harshitraj.me/>
________________________________

**Comment by abhishekshree** [comment]
what redundant

**Comment by abhishekshree** [comment]
codeql can ideally be scheduled for once in a week only, if we have gosec

**Pull request merged**
