### PR TITLE
removed APC access to past year batches

### PR DESCRIPTION
**Pull request by Krishnansh5**
- removed APC access from students that are not Y21

### CODE REVIEW

**Comment by 1-Harshit** [comment]
Why limiting to ug students?

**Comment by Krishnansh5** [comment]
Agrim asked for this change to show only UG21 to APCs

**Comment by 1-Harshit** [comment]
No.

Cc: @abhishekshree

**Comment by abhishekshree** [comment]
> Agrim asked for this change to show only UG21 to APCs

This never happens.

**Comment by abhishekshree** [comment]
Also requests like these should come through the RAS repo

**Comment by 1-Harshit** [comment]
I know showing of entire data is wrong and discussions are going on but such logics are not appropriated.

Come with a viable option.

**Comment by 1-Harshit** [comment]
> Also requests like these should come through the RAS repo

Please note this. Don't make any exception if you want to see RAS work in long run.

@spo-iitk/web-head-2023

**Comment by abhishekshree** [comment]
Bruh what is UG21 only to UG21 APCs

**Comment by 1-Harshit** [comment]
But we do have the grad year, right?

**Comment by abhishekshree** [comment]
not expected grad year sir

**Comment by abhishekshree** [comment]
also would be still difficult, ek year k APC bas apne year + 2 tak k students dekh payenge?

**Pull request closed without merging**
